```{r, header-mongoDB, echo = F}
########################################################################################## #
#'  Arquivo utilizado para envio das bases para o servidor mongoDB
#' 
#'  Autor: Mikael Marin Coletto
#'  Data: 11/03/23
########################################################################################## #

## 0.1 - Bibliotecas e scripts fontes----
library(mongolite)
library(dbplyr)
```

```{r, config}

## Dados padrão do mongo
mongo_db_user <- config::get("mongo_db_user", file = here::here("config/config.yml"))
mongo_db_password <- config::get("mongo_db_password", file = here::here("config/config.yml"))
mongo_db_url_extra <- config::get("mongo_db_url_extra", file = here::here("config/config.yml"))
mongo_database <- config::get("mongo_database", file = here::here("config/config.yml"))

url_srv <- paste0("mongodb+srv://", mongo_db_user, ":", mongo_db_password, mongo_db_url_extra)

mongo_collection <- config::get("mongo_collection_counts", file = here::here("config/config.yml"))
mongo_db <- mongolite::mongo(collection = mongo_collection, db = mongo_database, url = url_srv, verbose = TRUE)

```

```{r}

## Inserindo dados da base 1 raw
db_games_1_raw <- data.table::fread(here::here("data-raw/steam-data/db-1/games.csv"))
mongo_db <- mongolite::mongo(collection = "db-games-1-raw", db = mongo_database, url = url_srv, verbose = TRUE)
mongo_db$drop()
mongo_db$insert(db_games_1_raw)

## Inserindo dados da base 3 raw
db_games_3_raw <- data.table::fread(here::here("data-raw/steam-data/db-3/games.csv"))
mongo_db <- mongolite::mongo(collection = "db-games-3-raw", db = mongo_database, url = url_srv, verbose = TRUE)
mongo_db$drop()
mongo_db$insert(db_games_3_raw)

## Inserindo dados da base 1 tratada
db_games_1 <- data.table::fread(here::here("data-raw/created-tables/db-games-1.csv"))
mongo_db <- mongolite::mongo(collection = "db-games-1", db = mongo_database, url = url_srv, verbose = TRUE)
mongo_db$drop()
mongo_db$insert(db_games_1)
```
